[tool.flake8]
application-import-names = ['clash_of_code', 'contests', 'duet', 'homepage', 'problems', 'submissions', 'users']
exclude = [".git","__pycache",".venv","*migrations/"]
import-order-style = "google"
max-line-length = 88

[tool.black]
line-length = 88
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
(
  .vscode
  |venv
  |.venv
  |migrations/
  |.git
  |__pycache__/
  |__init__.py
  |fixtures/
  |requirements/
  |.gitignore
  |template.env
  |.env
  |.flake8
)
'''